version: '3.1'
services:
  main-app:
    build:
      context: ./Winery Gallery
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
comment-api:  
    build:
      context: ./CommentAPI  
      dockerfile: Dockerfile  
    ports:
      - "8081:8081"  
    depends_on:
      - database
      - main-app

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: winery-website
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin


