version: '3.1'
services:
  main-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: winery-website
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin


